### ISSUE TITLE
possible to use esp-01/esp-12?

### ISSUE THREAD

**Issue by sp0ok3r** [MichaelHeimann/OpenNETek#1]
Is it possible to make an "simpler" version,and use esp 01 or esp12 etc?

**Comment by MichaelHeimann** [comment]
Hi, this is very likely. With similar size, prices (around 3$ for the chip alone) and the option to use bluetooth with the ESP32, I was aiming for that chip, though.
Also: a lot of the ESP modules come with on-PCB antenna. Some additionally offer a u.fl to connect but need soldering to actually use it (e.g. D1 Mini Pro)

**Comment by MichaelHeimann** [comment]
I've just ordered an ESP32-C3 ( https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started) which I will try out when it arrives (early april).
It is much smaller than the ESP32-wroom32u, more power-efficient and still able to run the core (hopefully ;) ) without changes.
I'll test and update here.

**Comment by MichaelHeimann** [comment]
OK, I've tried the code on the ESP32-C3 and it doesn't work right away. The good thing is that it only needs a very small change to work. (https://github.com/atc1441/NETSGPClient/pull/27) 

For me, the size was important and the ESP32-C3 is barely larger than the LC12S and does have a ESP32, USB-C and the u.fl on it.

**Comment by MichaelHeimann** [comment]
Since the patch was taken info NETSGPClient (yay, my first patch, I'm happy :D ) the ESP32-C3 is supported.
I consider that the best platform for this project for price, size and power usage reasons compared to ESP8266 or ESP32.
