### ISSUE TITLE
No values 

### ISSUE THREAD

**Issue by ButteredPotatos** [MichaelHeimann/OpenNETek#2]
Hey, I have made some changes to my inverter (SG700MD) based on this instructions. I used an ESP32 and flashed it with this software. The ESP32 is working and hosting the web server. I entered the inverter ID and my WiFi details, but the web server is not displaying any values from my inverter. All the values are showing as zero.

Initially, I thought I might have interchanged the RX and TX pins, so I changed them, but it still won't display any values.

Can anyone help me with this problem?

**Comment by ButteredPotatos** [comment]
I forgot to mention that I flashed the ESP32 with version 3.0 of your software. The board I used is similar to the ESP32 CAM model, but I disabled the LED flash by desoldering the transistor for the LED.

**Comment by MichaelHeimann** [comment]
Is the Inverter ID showing correctly at /config?
There were cases where the id on the label was not really the ID that the firmware of the inverter used. (https://github.com/atc1441/NETSGPClient/issues/14#issuecomment-1166631557) 
Hope this is not one of these.

**Comment by MichaelHeimann** [comment]
> I forgot to mention that I flashed the ESP32 with version 3.0 of your software. The board I used is similar to the ESP32 CAM model, but I disabled the LED flash by desoldering the transistor for the LED.

Do you maybe have a link to the pinout of your (dev-)board?
When I google ESP32 CAM, I get [here](https://cdn.shopify.com/s/files/1/1509/1638/files/ESP32-Cam_DE.pdf?v=1642700051) and this doesn't have GPIO17 which I used for TX in the ESP32 firmware.

**Comment by ButteredPotatos** [comment]
> > I forgot to mention that I flashed the ESP32 with version 3.0 of your software. The board I used is similar to the ESP32 CAM model, but I disabled the LED flash by desoldering the transistor for the LED.
> 
> Do you maybe have a link to the pinout of your (dev-)board?
> When I google ESP32 CAM, I get [here](https://cdn.shopify.com/s/files/1/1509/1638/files/ESP32-Cam_DE.pdf?v=1642700051) and this doesn't have GPIO17 which I used for TX in the ESP32 firmware.

Thanks, that was actually the problem. I just saw the labels Rx and Tx on the board and didn't realize that they weren't referring to pins 16 and 17. I ended up soldering the two wires directly onto the ESP Wroom, and although it wasn't a very clean job, it works now.

Thank you very much for your fast help!
![IMG_20230421_180029.jpg](https://user-images.githubusercontent.com/57873219/233690671-aec4dd29-914a-417d-9340-93cccbc09fde.jpg)
