### ISSUE TITLE
reported power seems to be only half of the truth

### ISSUE THREAD

**Issue by MichaelHeimann** [MichaelHeimann/OpenNETek#4]
Thanks for your reply and of course for your work with Opennetek Michael, 
I didn´t know that inverter only has one mppt... 
I have to do more tests but yesterday with a lot of sun, panels current was 10 amps and voltage 27V  (more or less 270W) with opennetTek and almost 500W measured in AC with a smart plug that gives you consumption.. 
Because of that I thought it was measuring only one panel....  I will do more tests....

_Originally posted by @essrirm in https://github.com/MichaelHeimann/OpenNETek/issues/3#issuecomment-1570277757_

**Comment by MichaelHeimann** [comment]
Hi @essrirm !
I've today seen acP numbers far above 400W on a sg700 which has a rated output of 650W. So 50% can be ruled out.

I'll go and connect my inverter to a shelly plug instead of just measuring the phase in the breakerbox together with all other consumers.

Can you reproduce getting far lower numbers on the opennetek webpage than on a connected smart plug?

Regards,
Michael

**Comment by essrirm** [comment]
Hi, 

I did more tests and problem was that smart plug with Tuya app had a lot of delay.

It seems that smart plug usually gives you more generation, but it is like 10% more, not double.  It could be because smart plug is really cheap...

**Comment by MichaelHeimann** [comment]
I finally could test my inverter with a shelly plug s and the shelly did report e.g. 364W when the inverter reported 443W.

So there is quite a difference of somewhere  around 10 to 20 percent.

I think this might be the (in)efficiency (output vs input) but I do not know for sure.

Surely not 50%.
